Algoritmo "Entrada e Saida de Dados"

// Descrição   : Entrada e Saida de Dados
// Autor(a)    : marcusolindo
// Data atual  : 1/15/2022
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro
   
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Digite o seu nome")
   leia(nome)
   escreval("Digite a sua idade")
   leia(nota)
   
   escreval("O nome digitado foi: ", nome)
   escreval("A idade digitada foi: ", nota)
   
Fimalgoritmo