Algoritmo "Operedores aritiméticos"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcus
// Data atual  : 1/17/2022
Var
// Seção de Declarações das variáveis 
   resultado, valor01, valor02, valor03: real
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   valor01 := 10
    valor02 := 10
     valor03 := 10
   resultado := ((valor01 + valor02 + valor02) / valor03) % 2
   escreval("Resultado:", resultado)

Fimalgoritmo