Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : alguma coisa
// Autor(a)    : marcus lindoso
// Data atual  : 1/15/2022
Var
// Seção de Declarações das variáveis 
//primeiro nome
//segundo nome
//idade
//cidade
//endereço

          primeiroNome, segundoNome, cidade, endereco: caractere
          idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo